### ISSUE TITLE
Orange pi 5 plus ARM CPU

### ISSUE THREAD

**Issue by InfernalWolf666** [Castro-Fidel/PortProton_PKGBUILD#13]
Хочу поиграть в игры на своем апельсиновом куске ....
Но там процессор arm
есть ли способ подружить игры с arm процессором и как ?

Я в вашем линуксе в первые

**Comment by Castro-Fidel** [comment]
PortProton не планируется в ближайшее время портировать на arm.

**Comment by InfernalWolf666** [comment]
Very bad. It would be cool
